## The root configuration file for [popuko](https://github.com/voyagegroup/popuko)

# The version of this configuration format.
config_version = 0

# The port number which this application listening.
port = 3000

[github]
# This bot name for GitHub.
botname = "popuko"

# GitHub API Token
api_token = "api_token"

# GitHub Webhook secret
webhook_secret = "webhook_secret"

# url for enterprise. When not set, use github.com.
# base_url = https://example.com/api/v3
# upload_url = https://example.com/api/v3/upload


# For security reasons, you can restrict a repository which this bot supports.
#   - If this list is empty, this bot accepts all webhook incoming from any repositories.
#   - Otherwise, this bot only accepts the webhook from repositories listed in this item.
accepted_repositoies = [ "voyagegroup/popuko" ]
